### ISSUE TITLE
Open SMS application

### ISSUE THREAD

**Issue by maxsin** [rkkr/direct-sms-widget#6]
DESCRIPTION
Unable to send SMS through custom messaging app. When setting 'Open SMS Application' a message that is complaining about stock messaging app not being the default is displayed. 

STEPS
Add a new item from the screen
Set the Widget Click Action to Open SMS Application 
Define all the required fields
Get to the desktop and click on the newly created widget
Instead of opening the Messages application (one that's set as default) there is an error message complaining about stock messaging app not being the default. 

EXPECTED
SMS message to be opened in a custom messaging app.

OBSERVATIONS
When sending without confirmation the message sent does not appear in any messages app.

Direct SMS Widget v0.1.13
DEVICE version: Samsung S7 with Android 7.0

**Comment by rkkr** [comment]
This application is not maintained any more. I can't push any updates because it violates current Play store policies (background SMS sending is prohibited).
